# Generated by Django 3.1.1 on 2020-10-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
