# Generated by Django 3.1.1 on 2020-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='twoja stara', max_length=63),
            preserve_default=False,
        ),
    ]
